name: ml-visualization
channels:
- conda-forge
- anaconda
dependencies:
- conda-forge::python=3.7.3
- conda-forge::scikit-learn=1.0.2
- anaconda::pandas=1.1.3
- conda-forge::jupyterlab=3.2.8
- conda-forge::jupyterlab_widgets=1.0.2
- conda-forge::ipywidgets=7.6.5
- conda-forge::seaborn=0.11.2
- conda-forge::plotly=5.5.0
- conda-forge::nodejs=17.4.0
- conda-forge::pyarrow=6.0.1
- conda-forge::kaggle=1.5.16
- conda-forge::pygwalker=0.2.1
- conda-forge::statsmodels=0.13.5